//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Capricorn.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CAPRICTYPE                  129
#define IDD_PANEL                       130
#define ID_VIEW                         131
#define IDD_CONTROLS1                   131
#define IDD_TREE                        131
#define IDI_CAPRICORN                   132
#define IDD_RANGE                       132
#define IDD_BASE                        133
#define IDD_MEDIAN                      134
#define IDB_LB_IMG                      135
#define IDD_MENU                        135
#define IDB_TREE_LIST                   136
#define IDD_DIFF                        136
#define IDD_ANALYSE                     137
#define IDB_CYCLOPS                     138
#define IDD_CALC                        139
#define IDD_LIST                        140
#define IDB_TREE                        141
#define IDI_LOWER                       142
#define IDI_UPPER                       143
#define IDI_CURRENT                     144
#define IDD_RESULTS                     145
#define IDD_FLAGS                       146
#define IDD_IMPORT                      147
#define IDD_INFO                        148
#define IDB_LONG_GREEN                  149
#define IDB_TL_OFF                      150
#define IDC_CAP                         1000
#define IDC_BUT_START                   1001
#define IDC_DATASETS                    1006
#define IDC_START_DAY                   1007
#define IDC_START_MONTH                 1008
#define IDC_START_YEAR                  1009
#define IDC_END_MONTH                   1010
#define IDC_END_DAY                     1011
#define IDC_END_YEAR                    1012
#define IDC_BUT_APPLY_LIMITS            1013
#define IDC_APPLY_LIMITS                1014
#define IDC_BASE_ZERO                   1015
#define IDC_NORMAL                      1016
#define IDC_INVERT                      1017
#define IDC_TREE                        1018
#define IDC_BUT_APPLY                   1019
#define IDC_BUT_LIMITS                  1020
#define IDC_BUT_RET                     1021
#define IDC_BUT_MED                     1025
#define IDC_EDIT_RANGE                  1026
#define IDC_BUT_HIDE_MED                1027
#define IDC_EDIT_RANGE2                 1028
#define IDC_MENU_RANGE                  1029
#define IDC_MENU_MEDIAN                 1030
#define IDC_BUT_DIFF                    1030
#define IDC_BUT_DIFF1                   1030
#define IDC_MENU_DIFF                   1031
#define IDC_BUT_ANALYSE                 1034
#define IDC_EDIT_FLAG                   1035
#define IDE_BL                          1035
#define IDC_EDIT_FLAG2                  1036
#define IDE_RL                          1036
#define IDC_EDIT_START                  1037
#define IDE_IN                          1037
#define IDC_OUTPUT                      1038
#define IDC_GAIN                        1039
#define IDC_SPIN                        1040
#define IDS_GNY                         1040
#define IDC_BUT_DIFF2                   1041
#define IDE_BU                          1041
#define IDC_BUT_DIFF3                   1042
#define IDE_BC                          1042
#define IDE_RU                          1043
#define IDE_RR                          1043
#define IDC_SPIN2                       1044
#define IDE_RC                          1044
#define IDC_RAD_D1                      1045
#define IDC_RAD_D2                      1046
#define IDC_ZOOM                        1047
#define IDC_RAD_D3                      1047
#define IDC_PAN                         1048
#define IDE_ML                          1051
#define IDE_MU                          1052
#define IDE_MC                          1053
#define IDC_BI                          1054
#define IDE_ADD_VAL                     1055
#define IDE_ADD_MONTH                   1056
#define IDE_ADD_DAY                     1057
#define IDE_ADD_YEAR                    1058
#define IDC_BUT_NEW_APPLY               1059
#define IDC_MENU_FLAGS                  1060
#define IDC_SPIN_MODE                   1061
#define IDC_RES_NUM                     1062
#define IDC_BUT_PROCESS                 1066
#define IDC_PROG                        1068
#define IDC_BUT_END                     1069
#define IDC_TREECTRLS                   1073
#define IDC_TREEDATA                    1074
#define IDS_MONTH                       1075
#define IDS_DAY                         1076
#define IDS_YEAR                        1077
#define IDS_VAL                         1078
#define IDC_SPIN_DATE                   1079
#define IDC_BUT_UPDATE                  1080
#define IDC_EDIT1                       1081
#define IDE_TT                          1081
#define IDE_CURRENCY                    1081
#define IDE_COL_DATE                    1081
#define IDS_RESOLUTION                  1081
#define IDC_BUT_UNDO                    1082
#define IDE_COL_VAL                     1082
#define IDS_GAIN                        1083
#define IDC_BUT_UP                      1085
#define IDC_BUT_DOWN                    1086
#define IDS_MAXV                        1087
#define IDE_MAXV                        1087
#define IDS_MAXA                        1088
#define IDE_MINV                        1088
#define IDS_MINV                        1089
#define IDE_MAXA                        1089
#define IDS_MINA                        1090
#define IDE_MINA                        1090
#define IDE_COMMENT                     1092
#define IDB_MOVE_UP                     1102
#define IDB_DELETE                      1103
#define IDC_SLIDER                      1105
#define IDR_FINE                        1107
#define IDR_COARSE                      1108
#define IDC_EDIT2                       1113
#define ID_REFRESH_DATA                 32771
#define ID_IMPORT                       32772
#define IDS_DATE                        61204
#define IDS_CURRENCY                    61205
#define IDS_RECOMMEND                   61206
#define IDS_CONVERSION                  61207
#define IDS_LEFT                        61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
